<#
.SYNOPSIS
    Part of the temporary Classic "Forever" beta SavedVariables workaround
    (see ForeverSVFallback.lua and ForeverSVBackup.lua in the addon itself).

.DESCRIPTION
    The Forever beta client writes EmbolsaoDB/EmbolsaoCharDB to disk
    correctly on every logout and /reload, but fails to hand them back to
    the addon on the client's own next load -- confirmed for other addons
    too (Questie, Auctionator), no official acknowledgment from Blizzard.
    ForeverSVFallback.lua already covers the /reload case via CVars, which
    live only as long as the client process does. This script covers the
    gap: a full client restart.

    It polls every "Embolsao.lua" SavedVariables file under the Forever
    beta account (account-wide + one per character) every few seconds, and
    the moment any of their timestamps change, rebuilds a single combined
    file, ForeverSVBackup.lua, in the DEPLOYED addon folder (not the git
    repo -- Embolsao isn't symlinked there on this machine, something else
    copies the repo over). On the addon's next load, if EmbolsaoDB/
    EmbolsaoCharDB come back nil, it reads that file as a second fallback
    source alongside the CVar one.

    2026-09-22: rewritten from a FileSystemWatcher + Register-ObjectEvent
    design after that one silently stopped reacting to changes after
    running for a couple of hours (process still alive, event subscriptions
    apparently dead -- exact cause not pinned down). Plain polling has none
    of that machinery's failure modes -- no events, no timers, nothing that
    can silently stop firing -- at the cost of a few seconds' worst-case
    delay, which does not matter here.

    Run once via .\install-task.ps1 (same folder) to have this start
    automatically at every Windows logon -- after that, nothing to remember.

.NOTES
    Requires PowerShell 5.1+ (ships with Windows). No external modules.
#>

$ErrorActionPreference = "Stop"

# ---------------------------------------------------------------------------
# Config -- edit if your install/account differs.
# ---------------------------------------------------------------------------
$WowRoot       = "C:\Games\World of Warcraft\_classic_beta_"
$AccountId     = "1014236#1"
$AddOnOutput   = Join-Path $WowRoot "Interface\AddOns\Embolsao\ForeverSVBackup.lua"
$PollInterval  = 5 # seconds

$AccountRoot = Join-Path $WowRoot "WTF\Account\$AccountId"

# ---------------------------------------------------------------------------
# Extraction: SavedVariables files are literal Lua -- "<Global> = { ... }"
# and nothing else -- so pull the table literal out with a greedy regex
# (first "{" after "=" to the LAST "}" in the file) instead of a real Lua
# parser. Read-retry a few times: the client can hold a brief lock right
# after writing.
# ---------------------------------------------------------------------------
function Read-TableLiteral {
    param([string]$Path, [string]$GlobalName)

    for ($attempt = 1; $attempt -le 5; $attempt++) {
        try {
            $text = [System.IO.File]::ReadAllText($Path)
            if ($text -match "(?s)$GlobalName\s*=\s*(\{.*\})\s*\z") {
                return $Matches[1]
            }
            return $null
        } catch [System.IO.IOException] {
            Start-Sleep -Milliseconds 300
        }
    }
    Write-Warning "Could not read $Path after retries (still locked?)."
    return $null
}

function Get-CharKey {
    param([string]$SavedVariablesPath)
    # ...\WTF\Account\<Acct>\<Realm>\<Character>\SavedVariables\Embolsao.lua
    $charFolder  = Split-Path (Split-Path $SavedVariablesPath -Parent) -Parent
    $realmFolder = Split-Path $charFolder -Parent
    return "$(Split-Path $charFolder -Leaf)-$(Split-Path $realmFolder -Leaf)"
}

function Rebuild-Backup {
    $accountFile = Join-Path $AccountRoot "SavedVariables\Embolsao.lua"
    if (-not (Test-Path $accountFile)) {
        Write-Host "$(Get-Date -Format 'HH:mm:ss') no account SavedVariables yet, skipping."
        return
    }

    $dbLiteral = Read-TableLiteral -Path $accountFile -GlobalName "EmbolsaoDB"
    if (-not $dbLiteral) {
        Write-Host "$(Get-Date -Format 'HH:mm:ss') account file has no EmbolsaoDB yet, skipping."
        return
    }

    $charEntries = New-Object System.Collections.Generic.List[string]
    Get-ChildItem -Path $AccountRoot -Filter "Embolsao.lua" -Recurse -ErrorAction SilentlyContinue |
        Where-Object { $_.FullName -like "*\SavedVariables\Embolsao.lua" -and $_.FullName -ne $accountFile } |
        ForEach-Object {
            $charLiteral = Read-TableLiteral -Path $_.FullName -GlobalName "EmbolsaoCharDB"
            if ($charLiteral) {
                $key = Get-CharKey -SavedVariablesPath $_.FullName
                $charEntries.Add("        [`"$key`"] = $charLiteral,")
            }
        }

    $sb = New-Object System.Text.StringBuilder
    [void]$sb.AppendLine("-- Auto-generated by tools/ForeverSVWatcher.ps1 -- do not edit by hand.")
    [void]$sb.AppendLine("-- Last updated: $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')")
    [void]$sb.AppendLine("Embolsao_ForeverBackup = {")
    [void]$sb.AppendLine("    db = $dbLiteral,")
    [void]$sb.AppendLine("    chars = {")
    foreach ($entry in $charEntries) { [void]$sb.AppendLine($entry) }
    [void]$sb.AppendLine("    },")
    [void]$sb.AppendLine("}")

    $tempPath = "$AddOnOutput.tmp"
    [System.IO.File]::WriteAllText($tempPath, $sb.ToString())
    Move-Item -Path $tempPath -Destination $AddOnOutput -Force

    Write-Host "$(Get-Date -Format 'HH:mm:ss') backed up EmbolsaoDB + $($charEntries.Count) character(s) -> $AddOnOutput"
}

# ---------------------------------------------------------------------------
# Poll loop: every $PollInterval seconds, check every watched file's
# LastWriteTime against what was last seen; rebuild once if anything moved.
# Simple and easy to reason about on purpose -- see the 2026-09-22 note above.
# ---------------------------------------------------------------------------
if (-not (Test-Path $AccountRoot)) {
    throw "Account folder not found: $AccountRoot -- check `$AccountId at the top of this script."
}

Write-Host "Polling $AccountRoot for Embolsao.lua changes every ${PollInterval}s (Ctrl+C to stop)..."
Rebuild-Backup # catch up immediately in case something changed while this wasn't running

$lastSeen = @{}
Get-ChildItem -Path $AccountRoot -Filter "Embolsao.lua" -Recurse -ErrorAction SilentlyContinue |
    ForEach-Object { $lastSeen[$_.FullName] = $_.LastWriteTimeUtc }

while ($true) {
    Start-Sleep -Seconds $PollInterval

    $changed = $false
    $seenNow = @{}
    Get-ChildItem -Path $AccountRoot -Filter "Embolsao.lua" -Recurse -ErrorAction SilentlyContinue |
        ForEach-Object {
            $seenNow[$_.FullName] = $_.LastWriteTimeUtc
            if (-not $lastSeen.ContainsKey($_.FullName) -or $lastSeen[$_.FullName] -ne $_.LastWriteTimeUtc) {
                $changed = $true
            }
        }
    $lastSeen = $seenNow

    if ($changed) {
        Rebuild-Backup
    }
}
